version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - CONTAINER_NAME=${CONTAINER_NAME}
        - IMAGE_NAME=${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    ports:
      - "3000:3000"