name: Build and Deploy to AWS Lightsail

on:
  push:
    branches:
      - main
      - dev


env:
  AWS_REGION: us-east-1
  MAIN_SERVICE_NAME: smartspeak
  DEV_SERVICE_NAME: smartspeak-dev
  MAIN_CONTAINER_NAME: smartspeak-container
  DEV_CONTAINER_NAME: smartspeak-container-dev
  MAIN_IMAGE_NAME: smartspeak-image
  DEV_IMAGE_NAME: smartspeak-image-dev

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build Docker Image
        run: docker build -t ${{ getServiceName }}:release .
      - name: Push and Deploy
        run: |
          service_name=${{ getServiceName }}
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label ${service_name} \
            --image ${service_name}:release
          aws lightsail get-container-images --service-name ${service_name} | jq --raw-output ".containerImages[0].image" > image.txt
          jq --arg image $(cat image.txt) '.containers.app.image = $image' container.template.json > container-updated.json
          jq --arg databaseUrl ${{ secrets.DATABASE_MAIN_URL }} '.containers.app.environment["DATABASE_URL"] = $databaseUrl' container-updated.json > container.json
          aws lightsail create-container-service-deployment --service-name ${service_name} --cli-input-json file://$(pwd)/container.json
    env:
      getServiceName: ${{ env.MAIN_SERVICE_NAME }}
      getContainerName: ${{ env.MAIN_CONTAINER_NAME }}
      getImageName: ${{ env.MAIN_IMAGE_NAME }}
    if: github.ref == 'refs/heads/main'

  build_and_deploy_dev:
    name: Build and Deploy (Dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build Docker Image
        run: docker build -t ${{ getServiceName }}:release .
      - name: Push and Deploy
        run: |
          service_name=${{ getServiceName }}
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label ${service_name} \
            --image ${service_name}:release
          aws lightsail get-container-images --service-name ${service_name} | jq --raw-output ".containerImages[0].image" > image.txt
          jq --arg image $(cat image.txt) '.containers.app.image = $image' container.template.json > container-updated.json
          jq --arg databaseUrl ${{ secrets.DATABASE_DEV_URL }} '.containers.app.environment["DATABASE_URL"] = $databaseUrl' container-updated.json > container.json
          aws lightsail create-container-service-deployment --service-name ${service_name} --cli-input-json file://$(pwd)/container.json
    env:
      getServiceName: ${{ env.DEV_SERVICE_NAME }}
      getContainerName: ${{ env.DEV_CONTAINER_NAME }}
      getImageName: ${{ env.DEV_IMAGE_NAME }}
    if: github.ref == 'refs/heads/dev'
